export const ORIGINS = {
  'Ïlmans': ['Ylin', 'Yäa', 'Metsa', 'Tovalínen', 'Haluh', 'Ilta', 'Lumni'],
  'Immortels': ['Híven', 'Shuul', 'Íö', 'Futio'],
  'Habitants': ['Laïhen', 'Métissé', 'Domp', 'Fhirios', 'Geikro', "Nah'nos", 'Druhandi', 'Korrigan', 'Mnenin', 'Eloslja', 'Durvo', 'Etarda', 'Oekug', 'Jatar', 'Nimbus', 'Sihelë', 'Mëpi', 'Ëlfya'],
  'Autres': ['Drakore', 'Marginaux', 'Autre']
}

export const TL_COLORS = {
  'Naissance':           { accent: '#7cb342', bg: 'rgba(124,179,66,0.15)',   icon: '◎' },
  'Mariage':             { accent: '#e91e63', bg: 'rgba(233,30,99,0.15)',    icon: '♥' },
  'Mort':                { accent: '#78909c', bg: 'rgba(120,144,156,0.15)',  icon: '†' },
  'Création ville':      { accent: '#f9a825', bg: 'rgba(249,168,37,0.15)',   icon: '⌂' },
  'Bataille':            { accent: '#d32f2f', bg: 'rgba(211,47,47,0.15)',    icon: '⚔' },
  'Nommage':             { accent: '#00acc1', bg: 'rgba(0,172,193,0.15)',    icon: '✦' },
  'Départ':              { accent: '#fb8c00', bg: 'rgba(251,140,0,0.15)',    icon: '→' },
  'Retour':              { accent: '#9e9d24', bg: 'rgba(158,157,36,0.15)',   icon: '↩' },
  'Transfert pouvoir':   { accent: '#8e24aa', bg: 'rgba(142,36,170,0.15)',   icon: '♛' },
  'Rencontre':           { accent: '#0288d1', bg: 'rgba(2,136,209,0.15)',    icon: '✦' },
  'Rébellion':           { accent: '#d84315', bg: 'rgba(216,67,21,0.15)',    icon: '!' },
  "Coup d'état":         { accent: '#c62828', bg: 'rgba(198,40,40,0.15)',    icon: '⚡' },
  'Événement':           { accent: '#6d4c41', bg: 'rgba(109,76,65,0.15)',    icon: '◆' },
  'Transformation':      { accent: '#7b1fa2', bg: 'rgba(123,31,162,0.15)',   icon: '✧' },
  'Arrivée':             { accent: '#689f38', bg: 'rgba(104,159,56,0.15)',   icon: '◉' },
  'Découverte':          { accent: '#ef6c00', bg: 'rgba(239,108,0,0.15)',    icon: '◈' },
  'Séparation':          { accent: '#ffa000', bg: 'rgba(255,160,0,0.15)',    icon: '↔' },
  'Tentative assassinat':{ accent: '#c62828', bg: 'rgba(198,40,40,0.15)',    icon: '✗' },
  'Exécution':           { accent: '#424242', bg: 'rgba(66,66,66,0.15)',     icon: '✝' },
  'Exil':                { accent: '#5d4037', bg: 'rgba(93,64,55,0.15)',     icon: '~' },
  'Emprisonnement':      { accent: '#455a64', bg: 'rgba(69,90,100,0.15)',    icon: '⛓' },
  'Libération':          { accent: '#558b2f', bg: 'rgba(85,139,47,0.15)',    icon: '◯' },
  'Reconstruction':      { accent: '#ff8f00', bg: 'rgba(255,143,0,0.15)',    icon: '✚' },
  'Guerre':              { accent: '#b71c1c', bg: 'rgba(183,28,28,0.15)',    icon: '⚔' },
  'Victoire':            { accent: '#558b2f', bg: 'rgba(85,139,47,0.15)',    icon: '★' },
  'Déclaration':         { accent: '#6a1b9a', bg: 'rgba(106,27,154,0.15)',   icon: '◈' },
  'Disparition':         { accent: '#37474f', bg: 'rgba(55,71,79,0.15)',     icon: '?' },
  'Achèvement':          { accent: '#f57f17', bg: 'rgba(245,127,23,0.15)',   icon: '✓' },
  'Création':            { accent: '#e65100', bg: 'rgba(230,81,0,0.15)',     icon: '⊕' },
}

export const TL_DEFAULT = { accent: '#8892a4', bg: 'rgba(136,146,164,0.1)', icon: '◆' }

export const TL_SEED = [
  { date: -9500, type: 'Naissance',    desc: "Naissance des ïlmans par l'accouplement des Ëlfya avec les Mëpi", chars: 'Ïlmans', lieu: 'Mas Haluho' },
  { date: -9500, type: 'Événement',    desc: 'Apparition des Drakores en Azaria', chars: 'Drakores', lieu: 'Azaria' },
  { date: -6890, type: 'Transformation', desc: 'Transformation des ïlmans en laïhens', chars: 'Laïhens', lieu: 'Mas Haluho' },
  { date: -6390, type: 'Départ',       desc: 'Début de la Longue Marche vers les Nouvelles Terres menée par Urval', chars: 'Urval le Meneur', lieu: 'Mas Haluho' },
  { date: -5495, type: 'Arrivée',      desc: 'Arrivée sur les Nouvelles Terres', chars: 'Urval et les laïhens', lieu: 'Mas Usien' },
  { date: -5495, type: 'Nommage',      desc: 'Nommage de Imthra Unaíné (Montagne Rouge)', chars: 'Urval', lieu: 'Montagne Rouge' },
  { date: -5495, type: 'Nommage',      desc: 'Nommage de Wamka Imthra Hiven (Grande Montagne Grise)', chars: 'Urval', lieu: 'Grande Montagne Grise' },
  { date: -5495, type: 'Découverte',   desc: 'Découverte de la forêt Alaysia', chars: 'Urval et les laïhens', lieu: 'Alaysia' },
  { date: -5494, type: 'Séparation',   desc: 'Séparation : Polcrit part vers les Grandes Montagnes Grises', chars: 'Polcrit le Grand', lieu: 'Xénos' },
  { date: -5492, type: 'Naissance',    desc: "Naissance de Satel, fils d'Urval et Ilette", chars: 'Satel, Urval, Ilette', lieu: 'Stalun' },
  { date: -5490, type: 'Création ville', desc: 'Construction de la Grande Cité Stalun au bord du Grand Lac', chars: 'Urval', lieu: 'Stalun' },
  { date: -5488, type: 'Nommage',      desc: 'Le Grand Lac nommé Stalun (eau)', chars: 'Urval', lieu: 'Stalun' },
  { date: -5482, type: 'Création ville', desc: "Création du Grand Port d'Elcros", chars: 'Elcros', lieu: "Port d'Elcros" },
  { date: -5481, type: 'Mariage',      desc: "Mariage d'Elcros avec Marila", chars: 'Elcros, Marila', lieu: "Port d'Elcros" },
  { date: -5480, type: 'Création ville', desc: 'Finalisation de Dura Perepi', chars: 'Perepi le Protecteur', lieu: 'Dura Perepi' },
  { date: -5475, type: 'Départ',       desc: 'Départ de Satel (17 ans) pour découvrir les Terres Nouvelles', chars: 'Satel, Racost, Milas', lieu: 'Stalun' },
  { date: -5474, type: 'Événement',    desc: "Rencontre désastreuse d'Urval avec les nains, perte de sa jambe", chars: 'Urval', lieu: 'Montagnes' },
  { date: -5463, type: 'Naissance',    desc: "Naissance de Lores, fils d'Elcros et Marila", chars: 'Lores, Elcros, Marila', lieu: "Port d'Elcros" },
  { date: -5454, type: 'Rencontre',    desc: 'Satel rencontre les laïhens de la colonie Deni', chars: 'Satel, Frotos, Iluine', lieu: 'Deni' },
  { date: -5453, type: 'Rencontre',    desc: "Satel rencontre la tribu d'Eirini", chars: 'Satel, Opila', lieu: 'Eirini' },
  { date: -5453, type: 'Mariage',      desc: 'Satel épouse Opila et devient chef', chars: 'Satel, Opila', lieu: 'Eirini' },
  { date: -5452, type: 'Création ville', desc: 'Début de construction de la Ville Blanche par Racost', chars: 'Racost, Iluine', lieu: 'Tisis' },
  { date: -5451, type: 'Événement',    desc: "Tora arrive à Stalun avec l'écriture Toral", chars: 'Tora, Urval', lieu: 'Stalun' },
  { date: -5449, type: 'Création ville', desc: 'Finalisation de la Ville Blanche', chars: 'Racost', lieu: 'Tisis' },
  { date: -5449, type: 'Mort',         desc: 'Mort de Lores de maladie', chars: 'Lores', lieu: "Port d'Elcros" },
  { date: -5449, type: 'Événement',    desc: "Introduction de l'écriture Toral généralisée", chars: 'Tora', lieu: 'Toutes les terres' },
  { date: -5449, type: 'Transfert pouvoir', desc: 'Urval lègue son pouvoir à Lecasar le Roux', chars: 'Urval, Lecasar', lieu: 'Stalun' },
  { date: -5449, type: 'Tentative assassinat', desc: "Tentative d'assassinat contre Urval par Melcros", chars: 'Urval, Melcros', lieu: 'Stalun' },
  { date: -5447, type: 'Naissance',    desc: 'Naissance de Malme, fille de Lecasar et Ilrenne', chars: 'Malme, Lecasar, Ilrenne', lieu: 'Stalun' },
  { date: -5446, type: 'Naissance',    desc: 'Naissance de Piros, deuxième fils de Perepi', chars: 'Piros, Perepi', lieu: 'Dura Perepi' },
  { date: -5441, type: 'Naissance',    desc: 'Naissance de Kilros, fils de Lecasar et Ilrenne', chars: 'Kilros, Lecasar, Ilrenne', lieu: 'Stalun' },
  { date: -5440, type: 'Création ville', desc: 'Création de Kilos Milas (Cercle de Milas)', chars: 'Milas', lieu: 'Kilos Milas' },
  { date: -5437, type: 'Départ',       desc: "Piros envoyé au port d'Elcros pour étudier", chars: 'Piros', lieu: "Port d'Elcros" },
  { date: -5425, type: 'Naissance',    desc: "Naissance d'Oline, fille de Piros et Carenne", chars: 'Oline, Piros, Carenne', lieu: 'Dura Perepi' },
  { date: -5424, type: 'Rébellion',    desc: 'Kilros se rebelle et part créer sa propre cité', chars: 'Kilros', lieu: 'Prasinos' },
  { date: -5422, type: 'Événement',    desc: 'Satel découvre que Zeril Satel a été envahie par des barbares', chars: 'Satel, Urtes', lieu: 'Zeril Satel' },
  { date: -5421, type: 'Rencontre',    desc: 'Rencontre de Satel avec Allentel et Solas', chars: 'Satel, Allentel, Solas', lieu: 'Zeril Satel' },
  { date: -5421, type: 'Bataille',     desc: 'Reprise de Zeril Satel aux barbares', chars: 'Satel, Allentel, Solas, Rolak', lieu: 'Zeril Satel' },
  { date: -5419, type: 'Bataille',     desc: 'Piros et Firnaros défont Kilros le Traître', chars: 'Piros, Firnaros, Kilros', lieu: 'Prasinos' },
  { date: -5418, type: 'Naissance',    desc: "Naissance d'Esler, fils d'Elcros et Marila", chars: 'Esler, Elcros, Marila', lieu: "Port d'Elcros" },
  { date: -5418, type: 'Événement',    desc: "L'armée de Rolak aide à reconstruire Zeril Satel", chars: 'Rolak, Satel', lieu: 'Zeril Satel' },
  { date: -5416, type: 'Naissance',    desc: 'Naissance de Kalem, second fils de Satel et Opila', chars: 'Kalem, Satel, Opila', lieu: 'Zeril Satel' },
  { date: -5396, type: 'Naissance',    desc: 'Naissance de Presil et Minfa, jumeaux enfants de Kilros et Risel', chars: 'Presil, Minfa, Kilros, Risel', lieu: 'Prasinos' },
  { date: -5393, type: 'Bataille',     desc: 'Chute de Kilros, défait par Firnaros et Esler', chars: 'Kilros, Firnaros, Esler', lieu: 'Prasinos' },
  { date: -5393, type: 'Exil',         desc: 'Kilros banni, part errer à Xénos', chars: 'Kilros', lieu: 'Xénos' },
  { date: -5392, type: 'Reconstruction', desc: 'Reconstruction de la cité de Kilros', chars: 'Esler, Firnaros, Lecasar', lieu: 'Prasinos' },
  { date: -5391, type: 'Création ville', desc: 'Finalisation de Silfis par Esler', chars: 'Esler', lieu: 'Silfis' },
  { date: -5391, type: 'Mariage',      desc: 'Mariage de Frotos et Malme', chars: 'Frotos, Malme', lieu: 'Racost' },
  { date: -5506, type: 'Création',     desc: 'Début de construction du Château Noir par Polcrit', chars: 'Polcrit le Grand', lieu: 'Xénos' },
  { date: -5508, type: 'Mariage',      desc: 'Mariage de Polcrit avec Talone', chars: 'Polcrit, Talone', lieu: 'Xénos' },
  { date: -5509, type: 'Naissance',    desc: 'Naissance de Greilia, fille de Polcrit et Talone', chars: 'Greilia', lieu: 'Xénos' },
  { date: -5511, type: 'Naissance',    desc: 'Naissance de Lizdri, fille de Polcrit et Talone', chars: 'Lizdri', lieu: 'Xénos' },
  { date: -5512, type: 'Naissance',    desc: "Naissance d'Orzia, fille de Polcrit et Talone", chars: 'Orzia', lieu: 'Xénos' },
  { date: -5514, type: 'Naissance',    desc: "Naissance d'Embor, premier fils de Polcrit et Genrat", chars: 'Embor', lieu: 'Xénos' },
  { date: -5516, type: 'Achèvement',   desc: 'Finalisation du Château Noir', chars: 'Polcrit', lieu: 'Xénos' },
  { date: -5516, type: 'Naissance',    desc: 'Naissance de Wymfi, second fils de Polcrit et Genrat', chars: 'Wymfi', lieu: 'Xénos' },
  { date: -5540, type: "Coup d'état",  desc: "Aanlin et Merly font un coup d'état, Tobor tue Polcrit", chars: 'Aanlin, Merly, Tobor, Polcrit', lieu: 'Xénos' },
  { date: -5540, type: 'Emprisonnement', desc: 'Embor et Wymfi emprisonnés dans les cachots', chars: 'Embor, Wymfi', lieu: 'Xénos' },
  { date: -5542, type: 'Libération',   desc: 'Lizdir et Rinor libèrent Embor et Wymfi', chars: 'Lizdir, Rinor, Embor, Wymfi', lieu: 'Xénos' },
  { date: -5543, type: 'Disparition',  desc: 'Disparition de Wynfi dans Alaysia', chars: 'Wynfi', lieu: 'Alaysia' },
  { date: -5545, type: 'Mariage',      desc: "Mariage d'Embor avec Gefala", chars: 'Embor, Gefala', lieu: 'Clan des Marais' },
  { date: -5546, type: 'Naissance',    desc: "Naissance du fils d'Embor et Gefala", chars: 'Embor, Gefala', lieu: 'Clan des Marais' },
  { date: -5552, type: 'Mort',         desc: 'Nora tue Wynar en duel, Ibis se jette de la falaise', chars: 'Nora, Wynar, Ibis', lieu: 'Xénos' },
  { date: -5552, type: 'Exécution',    desc: 'Exécution de Nora et torture/mort de Greilia', chars: 'Nora, Greilia', lieu: 'Xénos' },
  { date: -5556, type: 'Guerre',       desc: "Début de la guerre contre l'Empire", chars: 'Embor', lieu: 'Xénos' },
  { date: -5560, type: 'Victoire',     desc: "Victoire d'Aanlin, fin de la guerre", chars: 'Aanlin', lieu: 'Xénos' },
  { date: -5560, type: 'Déclaration',  desc: "Déclaration de l'Empire, les Terres nommées Xénos", chars: 'Aanlin', lieu: 'Xénos' },
  { date: -5560, type: 'Création ville', desc: 'Création de Lor Rinor à la frontière', chars: 'Rinor, Lizdir', lieu: 'Lor Rinor' },
  { date: -5565, type: 'Départ',       desc: 'Embor et Gefala partent visiter Perle', chars: 'Embor, Gefala', lieu: 'Perle' },
  { date: -5569, type: 'Naissance',    desc: "Naissance de Davrel, fils d'Embor et Gefala", chars: 'Davrel, Embor, Gefala', lieu: 'Nom Elcros' },
  { date: -5578, type: 'Mort',         desc: "Mort d'Embor de maladie et fatigue", chars: 'Embor', lieu: 'Stalun' },
  { date: -5583, type: 'Naissance',    desc: 'Naissance de Judith, fille de Milas et Solas', chars: 'Judith, Milas, Solas', lieu: 'Kilos Milas' },
  { date: -5589, type: 'Arrivée',      desc: 'Kilros arrive en Xénos', chars: 'Kilros', lieu: 'Xénos' },
  { date: -5590, type: 'Mort',         desc: "Mort d'Aanlin", chars: 'Aanlin', lieu: 'Xénos' },
  { date: -5590, type: 'Transfert pouvoir', desc: 'Kilros devient roi de Xénos', chars: 'Kilros', lieu: 'Xénos' },
  { date: -5591, type: 'Nommage',      desc: 'Renommage des lieux en langue Toral par Kilros', chars: 'Kilros', lieu: 'Xénos' },
  { date: -5591, type: 'Mariage',      desc: 'Mariage de Firnaros avec Léenne', chars: 'Firnaros, Léenne', lieu: 'Ville Blanche' },
  { date: -5592, type: 'Naissance',    desc: 'Naissance de Loiam, fils de Malme et Frotos', chars: 'Loiam, Malme, Frotos', lieu: 'Racost' },
  { date: -5592, type: 'Mariage',      desc: "Mariage d'Esler et Allentel", chars: 'Esler, Allentel', lieu: 'Silfis' },
  { date: -5592, type: 'Naissance',    desc: 'Naissance de Pelane, fille de Firnaros', chars: 'Pelane, Firnaros', lieu: 'Ville Blanche' },
  { date: -5593, type: 'Mort',         desc: "Mort d'Elcros à 95 ans", chars: 'Elcros', lieu: "Port d'Elcros" },
  { date: -5593, type: 'Transfert pouvoir', desc: 'Esler devient Roi de Perle', chars: 'Esler', lieu: 'Perle' },
  { date: -5593, type: 'Mort',         desc: 'Mort de Perepi', chars: 'Perepi', lieu: 'Dura Perepi' },
  { date: -5593, type: 'Transfert pouvoir', desc: 'Piros (39 ans) prend le trône à Dura Perepi', chars: 'Piros', lieu: 'Dura Perepi' },
  { date: -5594, type: 'Mort',         desc: "Mort d'Urval le Meneur", chars: 'Urval', lieu: 'Stalun' },
  { date: -5594, type: 'Naissance',    desc: "Naissance de Tulis, fils d'Esler et Allentel", chars: 'Tulis, Esler, Allentel', lieu: 'Silfis' },
  { date: -5595, type: 'Bataille',     desc: "Kilros tente d'attaquer Lor Rinor mais échoue face à Esler", chars: 'Kilros, Esler, Rinor', lieu: 'Lor Rinor' },
  { date: -5595, type: 'Naissance',    desc: "Naissance d'Ertesse, fils de Firnaros", chars: 'Ertesse, Firnaros', lieu: 'Ville Blanche' },
  { date: -5621, type: 'Mort',         desc: "Mort de Risel d'un cancer", chars: 'Risel', lieu: 'Lac de Risel' },
]
